{
    'name': 'City Custom Configurations',
    'license': 'LGPL-3',
    'version': '1.0',
    'author': 'Danny Santiago',
    'category': 'Customizations',
    'summary': 'Customizations for the city of Lewiston odoo instance. Updates to the employee form, res partner forms and portal view.',
    'depends': ['base', 'hr', 'portal', 'web', 'helpdesk', 'timesheet_grid'],
    'data': [
        'views/hr_employee_views.xml',
        'views/portal_layout.xml',
        'views/my_account_portal_view.xml',
        'views/res_partner_views.xml',
        'views/munis_res_partner.xml',
        'views/helpdesk_timesheet_update.xml',
        'views/assets.xml',
        'views/portal_custom_personal_ui.xml',
        'views/portal_personal_details_view.xml',
    ],
    'installable': True,
    'application': False,
}
